spring:
  application:
    name: integral-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: integral
    url: jdbc:mysql://localhost:3306/db_integral
    username: root
    password: 123456
server:
  port: 8081
  servlet:
    context-path: /integral